[build]
  command = "pnpm run test && pnpm build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "vite"
  framework = "#custom"
  targetPort = 5173
  port = 8888
  functions = "netlify/functions"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
