[build]
  command = "pnpm build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 5173         # Vite's default port
  port = 8888               # Netlify's proxy port
  functions = "netlify/functions"
