name: Deploy to Netlify

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env

      - name: Run unit tests
        run: pnpm test -- --run

  deploy:
    runs-on: ubuntu-22.04
    needs: test
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-netlify.outputs.deploy-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env

      - name: Lint code
        run: pnpm lint

      - name: Generate .env file
        run: |
          echo "VITE_ENVIRONMENT=production" >> .env
          echo "VITE_API_URL=https://twojadomena.pl" >> .env

      - name: Build app
        run: pnpm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        id: deploy-to-netlify
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Manual production deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
