name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-env

      - name: Run unit tests
        run: pnpm test -- --run

  # 🚫 Disabled Netlify deploy on PRs
  # deploy:
  #   runs-on: ubuntu-22.04
  #   environment:
  #     name: 'pull_request'
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setup-pnpm-env
  #
  #     - name: Lint code
  #       run: pnpm lint
  #
  #     - name: Build app
  #       run: pnpm run build
  #
  #     - name: Deploy to Netlify Preview
  #       uses: nwtgck/actions-netlify@v3.0
  #       with:
  #         publish-dir: './dist'
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         deploy-message: 'Deploy preview from PR #${{ github.event.pull_request.number }}'
  #         enable-pull-request-comment: true
  #         overwrites-pull-request-comment: true
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
